### ISSUE TITLE
Read files with ipfs CLI commands

### ISSUE THREAD

**Issue by zicmama** [justicenode/files_external_ipfs#2]
Yahoo!!  I was expecting your App for long. I have just installed it. 
Added a file to my new storage. All seems OK.

I used "nextcloud" as FolderName 

What would be the "ipfs get" command to read the file from CLI?

**Comment by zicmama** [comment]
Cannot find any filenames in pin ressources
```
for link in $(ipfs pin ls | awk '{print $1}'); do ipfs ls $link; done
```

**Comment by justicenode** [comment]
`ipfs files ls /nextcloud`
`ipfs files stat /nextcloud/filename`
hope this helps.

**Comment by zicmama** [comment]
Thanks, I can get file hash in 'stat'.
I wonder how "ipfs files" makes files visible and shared with other ipfs nodes?

**Comment by justicenode** [comment]
As far as I've understood the same way all other files work. It just adds a layer above that, that allows for location based access to files like in other filesystems.
